#PBS -N tde
#PBS -l nodes=1:ppn=24
#PBS -l walltime=24:00:00
#PBS -q gpu
#PBS -S /bin/bash
#PBS -V

NP=`cat $PBS_NODEFILE | wc -l`
NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`

cat $PBS_NODEFILE > /tmp/nodefile.$$
cd $PBS_O_WORKDIR
ulimit -s unlimited

module load apptainer/1.0.0
module load ovito/3.12

export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"
export LIBGL_ALWAYS_SOFTWARE=1
export QT_QPA_PLATFORM="offscreen"

export PATH=/opt/gcc/gcc-9.3.0/bin:${PATH}
export LIBRARY_PATH=/opt/gcc/gcc-9.3.0/lib:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/opt/gcc/gcc-9.3.0/lib64:$LD_LIBRARY_PATH
export C_INCLUDE_PATH=/opt/gcc/gcc-9.3.0/include:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=/opt/gcc/gcc-9.3.0/include:$CPLUS_INCLUDE_PATH

export CUDA_VISIBLE_DEVICES=1
export PATH=/home/changruiwang-ICME/Software/GPUMD-4.0/src:${PATH}

python test_tde.py >> output

